ci: update esphome to 2022.9.4
because platformio refuses to serve when platformio is older than
version 6.

> Error: Please upgrade to the PlatformIO Core 6